//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuongTrinhQLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLDETAIL
    {
        public int IDBill { get; set; }
        public int IDService { get; set; }
        public int Count { get; set; }
        public int TotalPrice { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
