//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuongTrinhQLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILL()
        {
            this.BILLDETAILS = new HashSet<BILLDETAIL>();
        }
    
        public int ID { get; set; }
        public int IDReceiveRoom { get; set; }
        public string StaffSetUp { get; set; }
        public Nullable<System.DateTime> DateOfCreate { get; set; }
        public int RoomPrice { get; set; }
        public int ServicePrice { get; set; }
        public int Surcharge { get; set; }
        public int TotalPrice { get; set; }
        public int Discount { get; set; }
        public int IDStatusBill { get; set; }
    
        public virtual RECEIVEROOM RECEIVEROOM { get; set; }
        public virtual STATUSBILL STATUSBILL { get; set; }
        public virtual STAFF STAFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILLDETAIL> BILLDETAILS { get; set; }
    }
}
