//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuongTrinhQLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKROOM()
        {
            this.RECEIVEROOMs = new HashSet<RECEIVEROOM>();
        }
    
        public int ID { get; set; }
        public int IDCustomer { get; set; }
        public int IDRoomType { get; set; }
        public System.DateTime DateBookRoom { get; set; }
        public System.DateTime DateCheckIn { get; set; }
        public System.DateTime DateCheckOut { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ROOMTYPE ROOMTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIVEROOM> RECEIVEROOMs { get; set; }
    }
}
