//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuongTrinhQLKS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManagement : DbContext
    {
        public HotelManagement()
            : base("name=HotelManagement")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BILL> BILLs { get; set; }
        public virtual DbSet<BILLDETAIL> BILLDETAILS { get; set; }
        public virtual DbSet<BOOKROOM> BOOKROOMs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<CUSTOMERTYPE> CUSTOMERTYPEs { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<RECEIVEROOM> RECEIVEROOMs { get; set; }
        public virtual DbSet<ROOM> ROOMs { get; set; }
        public virtual DbSet<ROOMTYPE> ROOMTYPEs { get; set; }
        public virtual DbSet<SERVICE> SERVICEs { get; set; }
        public virtual DbSet<SERVICETYPE> SERVICETYPEs { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<STAFFTYPE> STAFFTYPEs { get; set; }
        public virtual DbSet<STATUSBILL> STATUSBILLs { get; set; }
        public virtual DbSet<STATUSROOM> STATUSROOMs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<PARAMETER> PARAMETERs { get; set; }
    }
}
