//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuongTrinhQLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROOM()
        {
            this.RECEIVEROOMs = new HashSet<RECEIVEROOM>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int IDRoomType { get; set; }
        public int IDStatusRoom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIVEROOM> RECEIVEROOMs { get; set; }
        public virtual ROOMTYPE ROOMTYPE { get; set; }
        public virtual STATUSROOM STATUSROOM { get; set; }
    }
}
